Return Code: 0
Stdout: b"Database error: module 'dbm' has no attribute 'sqlite3'\nLocal var in thread: 10, [1, 2, 3], <class 'list'>\nDatabase error: module 'dbm' has no attribute 'sqlite3'\nDatabase error: module 'dbm' has no attribute 'sqlite3'\nDatabase error: module 'dbm' has no attribute 'sqlite3'\nDatabase error: module 'dbm' has no attribute 'sqlite3'\nLocal var in thread: 10, [1, 2, 3], <class 'list'>\nLocal var in thread: 10, [1, 2, 3], <class 'list'>\nLocal var in thread: 10, [1, 2, 3], <class 'list'>\nLocal var in thread: 10, [1, 2, 3], <class 'list'>\nAll threads finished.\nShared data: {0: -8, 4: 2, 3: -7, 1: 0, 2: 5}\n999998981695\nTime taken for os.times() (perf_counter): 0.000012\nposix.times_result(user=0.26, system=0.0, children_user=0.0, children_system=0.0, elapsed=4563460.85)\nTime taken for os.times() (process_time): 0.000001\nposix.times_result(user=0.26, system=0.0, children_user=0.0, children_system=0.0, elapsed=4563460.85)\nError when calling os.times with extra arguments\nError with dbm.sqlite3: module 'dbm' has no attribute 'sqlite3'\nProcessed data: [2, 4, 3, 10, 12345678901234567890, 0, 3, 2]\nOriginal object: 20, New object: 20\nOriginal object: new value, New object with string: new value\nSSL context created successfully\n"
Stderr: b''
