Return Code: 0
Stdout: b"Thread 0: Error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894323099200.\nThread 1: Error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894312613440.\nThread 2: Error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894228727360.\nThread 3: Error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894218241600.\nThread 4: Error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894207755840.\nDatabase operations completed.\nCalling os.times() with time_value=1.2345, flags=0\nResults: posix.times_result(user=0.02, system=0.0, children_user=0.0, children_system=0.0, elapsed=4563096.42)\nTrying with certificate at dummy.crt\nError during SSL Fuzzing: name 'socket' is not defined\n"
Stderr: b'Exception in thread Thread-1 (worker):\nException in thread Thread-2 (worker):\nException in thread Thread-3 (worker):\nException in thread Thread-4 (worker):\nException in thread Thread-5 (worker):\nTraceback (most recent call last):\nTraceback (most recent call last):\nTraceback (most recent call last):\nTraceback (most recent call last):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/665.py", line 13, in worker\n    cursor = db_conn.cursor()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/665.py", line 13, in worker\n    cursor = db_conn.cursor()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/665.py", line 13, in worker\n    cursor = db_conn.cursor()\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894207755840.\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894312613440.\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894218241600.\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/665.py", line 13, in worker\n    cursor = db_conn.cursor()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/665.py", line 13, in worker\n    cursor = db_conn.cursor()\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894228727360.\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 136894345516864 and this is thread id 136894323099200.\n'
