Return Code: 0
Stdout: b"Error in copy.replace(): replace() takes 1 positional argument but 2 were given\nnested_comp: [-60, 40, -60, 8, 24]\nRetrieved data: b'56595'\nTime difference: 1.725920210010372 seconds.\nDefault SSL context created successfully.\nThread 129095467796032: (6, 'Hello6')\nThread 129095455213120: (6, 'Hello6')\nThread 129095373424192: (6, 'Hello6')\nThread 129095362938432: (6, 'Hello6')\nThread 129095352452672: (6, 'Hello6')\nSuccessfully stored data with empty key.\nos.times() result: posix.times_result(user=0.07, system=0.0, children_user=0.0, children_system=0.0, elapsed=4561834.59), duration: 1.3828277587890625e-05\nSSL default context created successfully.\n"
Stderr: b'Exception in thread Thread-1 (complex_function2):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/326.py", line 60, in complex_function2\n    print(f"Thread {threading.get_ident()} accessing data:", thread_local_data.value)\n                                                             ^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: \'_thread._local\' object has no attribute \'value\'\n'
