Return Code: 1
Stdout: b''
Stderr: b'Exception in thread Thread-5 (threaded_function):\nException in thread Thread-1 (threaded_function):\nTraceback (most recent call last):\nTraceback (most recent call last):\nException in thread Thread-2 (threaded_function):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nException in thread Thread-3 (threaded_function):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTraceback (most recent call last):\nException in thread Thread-4 (threaded_function):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 32, in threaded_function\n    current_context = ctx.get()\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nLookupError: <ContextVar name=\'execution_context\' at 0x72d405e83790>\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 32, in threaded_function\n    current_context = ctx.get()\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 32, in threaded_function\n    current_context = ctx.get()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 32, in threaded_function\n    current_context = ctx.get()\nLookupError: <ContextVar name=\'execution_context\' at 0x72d405e83790>\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nLookupError: <ContextVar name=\'execution_context\' at 0x72d405e83790>\nLookupError: <ContextVar name=\'execution_context\' at 0x72d405e83790>\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 32, in threaded_function\n    current_context = ctx.get()\nLookupError: <ContextVar name=\'execution_context\' at 0x72d405e83790>\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 143, in <module>\n    main()\n    ~~~~^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/585.py", line 53, in main\n    with ctx.set("JIT_ON"):\n         ~~~~~~~^^^^^^^^^^\nTypeError: \'_contextvars.Token\' object does not support the context manager protocol\n'
