Return Code: 0
Stdout: b"Final counter: 10\nb'value1'\n20 world\nOS times result: posix.times_result(user=0.02, system=0.0, children_user=0.0, children_system=0.0, elapsed=4562543.28)\nSSL context created successfully.\nResult of annotated function: [2, 3, 4]\nos.times() took: 2.0919833332300186e-06\nCopy replace result: [1, 2, 42, 4, 5]\nSuccessfully created default context.\n"
Stderr: b'Exception in thread Thread-6 (<lambda>):\nException in thread Thread-7 (<lambda>):\nException in thread Thread-8 (<lambda>):\nException in thread Thread-9 (<lambda>):\nException in thread Thread-10 (<lambda>):\nTraceback (most recent call last):\nTraceback (most recent call last):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nTraceback (most recent call last):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 37, in <lambda>\n    thread = threading.Thread(target=lambda x=data[i]: jit_sensitive_function(x))\n                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 28, in jit_sensitive_function\n    for i in range(len(data)):\n                   ~~~^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 37, in <lambda>\n    thread = threading.Thread(target=lambda x=data[i]: jit_sensitive_function(x))\n                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^\nTypeError: object of type \'int\' has no len()\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 28, in jit_sensitive_function\n    for i in range(len(data)):\n                   ~~~^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 37, in <lambda>\n    thread = threading.Thread(target=lambda x=data[i]: jit_sensitive_function(x))\n                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 37, in <lambda>\n    thread = threading.Thread(target=lambda x=data[i]: jit_sensitive_function(x))\n                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 28, in jit_sensitive_function\n    for i in range(len(data)):\n                   ~~~^^^^^^\nTypeError: object of type \'int\' has no len()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 28, in jit_sensitive_function\n    for i in range(len(data)):\n                   ~~~^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 37, in <lambda>\n    thread = threading.Thread(target=lambda x=data[i]: jit_sensitive_function(x))\n                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^\nTypeError: object of type \'int\' has no len()\nTypeError: object of type \'int\' has no len()\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/412.py", line 28, in jit_sensitive_function\n    for i in range(len(data)):\n                   ~~~^^^^^^\nTypeError: object of type \'int\' has no len()\n'
